print("โปรดกรอกชื่อ")
name = str(input("ใส่ชื่อ"))
print("โปรดกรอกอายุ")
age = int(input("ใส่อายุ"))
print("โปรดกรอกรหัสประจำตัว")
stdID= int(input("ใส่รหัสประจำตัว"))
print("โปรดกรอกระดับชั้น")
Level = int(input("ใส่ระดับชั้น"))
print("โปรดกรอกชื่อเล่น")
nicname = str(input("ใส่ชื่อเล่น"))
print("โปรดกรอกส่วนสูง")
height= float(input("ใส่ส่วนสูง"))
print("โปรดกรอกน้ำหนัก")
weight= float(input("ใส่น้ำหนัก"))
print("ชื่อ : " + (name), "อายุ :"  + str(age)+"ปี")
print("รหัสประจำตัว : " + str(stdID) ,"ระดับชั้น :"  + str(Level))
print("ชื่อเล่น : " +(nicname))
print("ส่วนสูง : "+str(height) + "เซนติเมตร", "น้ำหนัก :"  +str(weight)+"เซนติเมตร")
sum = height + weight
print("ส่วนสูง + น้ำหนัก =",(sum))